### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by jaredgreener** [swluken/TouchTreeGrid#3]
I cannot get the examples to work when downloading the current master. The stores will load with data, but nothing is displayed.
![screen shot 2016-04-05 at 2 09 51 pm](https://cloud.githubusercontent.com/assets/2931865/14294762/3bfbb106-fb38-11e5-9d08-888bcfdacb76.png)

**Comment by swluken** [comment]
Hi,

This is due to an issue with newer version of Chrome as documented here:
http://www.ladysign-apps.com/developer/chrome-43-breaks-sencha-touch-modern-toolkit-and-how-to-fix-it/#.VwRvWaQrI2z

Touch 2.4.2 corrects this issue.  If you change the framework version in index.html/app.html in the various examples they should work for you.

TTG_KitchenSink/Index.html for example should read:

 "...src="http://cdn.sencha.com/touch/sencha-touch-2.4.2/sencha-touch-all-debug.js">..."

I'm working on a ExtJS 6 version of TouchTreeGrid for the modern toolkit and once complete I'll fix the other examples and update the repository (or remove the older ones).  As a side, the examples would work as is using FireFox.

Best regards,
Steve
